### ISSUE TITLE
Random superpower

### ISSUE THREAD

**Issue by he1k** [maechler/kurve#5]
Would be nice with a random option in superpower

**Comment by maechler** [comment]
@he1k Thanks for your feedback! There is a "random" superpower, however it is only chosen once in the very beginning and remains the same throughout all the rounds.

What do you mean by "random" option? Randomly chosen for each round? Or random each time it is used? Or maybe something else?

**Comment by maechler** [comment]
@he1k Any update from your side?

**Comment by pedromagician** [comment]
_Randomly chosen for each round?_

That sounds really good :)

**Comment by maechler** [comment]
I changed the random superpower to be random each round and released a new version!

**Comment by he1k** [comment]
Yes sorry coming back again, my intention was indeed random for every round :) Thank you!
