### ISSUE TITLE
Handle window resize

### ISSUE THREAD

**Issue by tim-we** [maechler/kurve#6]
Once the game has started and you resize the window the game area does not change. That is fine but I think after a round ends / before a new one starts the game area should be resized.

**Comment by maechler** [comment]
@tim-we Thanks for your feedback! You are absolutely right, this would be a nice addition. I wanted to avoid that someone could mess with the window size and kill an opponent that way. At the time it seemed the easiest way to implement it like this. However your recommended approach should not be too difficult either, I will have a look at it.

**Comment by maechler** [comment]
@tim-we I implemented this and released a new version!

**Comment by tim-we** [comment]
Awesome, thanks!
